### ISSUE TITLE
GameFactory interface default method

### ISSUE THREAD

**Issue by cesartecnicas** [tecnicas-g7/template-tp-grupal#13]
En algunas implementaciones de GameFactory se usa el método default makeLocationsAdjacent, pero en otras implementaciones directamente se hace lo mismo a mano.

**Comment by jaschulz** [comment]
Se implementa en Game (y se sobrecarga), sacandolo de GameFactory, y del resto de los otros lados donde estaba hecho a mano, o creado el mismo método.
