### ISSUE TITLE
Doc 4+1

### ISSUE THREAD

**Issue by cesartecnicas** [tecnicas-g7/template-tp-grupal#15]
Se había pedido documentación en el formato 4+1 dado en la primer clase.
No la encontré en la Wiki.

**Comment by cesartecnicas** [comment]
La doc de la entrega 2 son solo los diagramas de clase. Hay algo más?

**Comment by HikaruKirishima** [comment]
Dentro del enunciado solo se comentaba documentacion, no notamos que se requeria 4+1 puntualmente. Necesitaremos realizar la documentacion 4+1 de la 2da entrega mas los cambios que requiera la 3ra o directamente realizamos 4+1 de la 3ra?

**Comment by dgrico** [comment]
Documentación completa.
