### ISSUE TITLE
No dejar código comentado

### ISSUE THREAD

**Issue by cesartecnicas** [tecnicas-g7/template-tp-grupal#7]
ver 
https://github.com/tecnicas-g7/template-tp-grupal/blob/entrega1/src/main/java/ar/fiuba/tdd/tp/net/Server.java

https://github.com/tecnicas-g7/template-tp-grupal/blob/entrega1/src/main/java/ar/fiuba/tdd/tp/game/MainTest.java

**Comment by dgrico** [comment]
Issue solucionado en Branch “codeReviewed”.
