### ISSUE TITLE
Items particulares de cada juego

### ISSUE THREAD

**Issue by cesartecnicas** [tecnicas-g7/template-tp-grupal#8]
En general, en el modelo hay un montón de cosas particulares de cada juego: actions, items como Door, etc.

El modelo debería estar planteado a un nivel más alto de abstracción. Esto es condición para la segunda entrega.

Cierren éste issue en la entrega 2.

**Comment by cesartecnicas** [comment]
Amplio un poco.
**Container** tiene fields setear si tiene o no veneno. La clase está bien planteada a nivel genérico, pero el tema del veneno es particular de un juego. Los comandos también generan el string que se va a usar por pantalla. Esto sería una violación a SRP. El string que se genera con el mensaje tiene que ver con la presentación y no con la lógica del juego.

Los nombres **class Describable implements ContainerComponent** son muy confusos. Las interfaces se suelen nombrar como características o capacidades. En éste caso están invertidos.

La clase Describable agrega la capacidad de agregar actions, pero el nombre no es para nada claro. Se entiende que es algo describible (¿?).

No hay diferencia entre el engine y los juegos particulares. En el package game tiene clases generales y clases concretas de los juegos (como Door).

Para que sirve la clase Item?

``` java
Iterator<HashMap.Entry<String, Door>> it = origin.getDoorsIterator();
        while (it.hasNext()) {
            Door door = it.next().getValue();
```

for each?

Hay un montón de strings que no debería estar harcodeados ("You have to select an item!", "You can enter doors", "You have won the game!", etc.)

Las actions está definidas para juegos particulares.

Las conditions están mucho mejor planteadas.

**Comment by HikaruKirishima** [comment]
Modificamos la clase acciones a clase abstracta. Eliminamos las redundantes y adoptamos un archivo de mensajes.
