### ISSUE TITLE
Condiciones en Hanoi

### ISSUE THREAD

**Issue by cesartecnicas** [tecnicas-g7/template-tp-grupal#9]
Cambié el test de Hannoi

``` java
Game hanoiTower = ( new HanoiTower()).getGame();
Controller controller = new Controller(hanoiTower);

String command = "move stack1 stack3";
controller.interpretCommand(command);
String command2 = "move stack1 stack3";
controller.interpretCommand(command2);
```

y no explota.

Parece que no tienen condiciones al mover una de las fichas.

**Comment by jaschulz** [comment]
César, cambié el test para que corra tal cual el issue, y falla, tal cual lo esperado. ¿O te referís a que no lanza exception cuando hace controller.interpretCommand(command2);? Aguardamos tus comentarios.

**Comment by cesartecnicas** [comment]
El error no se debería manifestar al momento de mandar el comando?

Le hice un step y en ningún momento me decía que ese comando estaba mal.

**Comment by jaschulz** [comment]
Tal como lo hablamos ayer después de la clase, el funcionamiento es correcto.
